# Generated by Django 3.0.7 on 2020-06-14 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/default.jpeg', upload_to='profile_pics')),
                ('username', models.CharField(max_length=200, null=True)),
                ('pet', models.CharField(max_length=20, null=True)),
                ('pet_image', models.ImageField(default='/default_pet.png', upload_to='profile_pics')),
                ('pet_name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('breed', models.CharField(max_length=20, null=True)),
                ('pet_birthday', models.DateField(max_length=20, null=True)),
                ('pet_color', models.CharField(max_length=20, null=True)),
                ('notes', models.TextField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
